/*
_______________________________NOTES_______________________________
----> Poly means "many" and morphism means "ways to represent"...
----> So Polymorpism means "many ways to represent a single entity or item"...


____________________________Interesting Fact____________________________
----> Any language that does not support polymorphism, but support other concepts like encapsulation, we can refer them as "Object Based Language"... Example: ADA language
----> Since Java supports polymorphism, we can say that Java is "Object Oriented Language"...


__________________________Polymorphism Ways__________________________
----> One way of polymorphism is what we have used in the "Box" class and other classes in inheritance, i-e when the name of the constructor are same but the number of arguments were different and constructor with exact number and type of arguments was running based on the passed parameters...
----> And the other way of polymorphism is what we have seen that same function exists but does different operations...

__________________________Limitation_____________________________
----> Polymorphism does not apply on instance variables...
 */