/*
_______________________________NOTES_______________________________
----> Poly means "many" and morphism means "ways to represent"...
----> So Polymorpism means "many ways to represent a single entity or item"...


____________________________Interesting Fact____________________________
----> Any language that does not support polymorphism, but support other concepts like encapsulation, we can refer them as "Object Based Language"... Example: ADA language
----> Since Java supports polymorphism, we can say that Java is "Object Oriented Language"...


__________________________Polymorphism Ways__________________________
----> One way of polymorphism is what we have used in the "Box" class and other classes in inheritance, i-e when the name of the constructor are same but the number of arguments were different and constructor with exact number and type of arguments was running based on the passed parameters...
----> And the other way of polymorphism is what we have seen that same function exists but does different operations... Overriding and all...

__________________________Limitation_____________________________
----> Polymorphism does not apply on instance variables...
----> Example, if there are two classes A and B... B extends A... And if "A" contains (String name = "Abdullah") and B contains (String name = "Ahmed")... Then if the following is done:

A obj = new B();
if obj.name is printed then "Abdullah" will get printed... and if you want to print B's name then either you have to make "name" static inside B or the other method is to make the referenc variable of class B...
 */