/*
____________________________NOTES____________________________
----> Two classes, Base Class from which a new class is derived and a derive class are present in this concept... Derived class can have access to the properties and methods of the base class... Derived class can also have some aditional properties and methods...

----> As the child class is inheriting properties from the parent class example the variables... Then these variables need to get initialised for every child class... For example, there is a base class "Species" and there is a child class "Human"... "Species" has a variable "age" so whenever a new "Human" object will be made then for every object the age has to be initialised...
*/